FROM mcr.microsoft.com/dotnet/core/sdk as build
WORKDIR /aspnet
COPY . .
RUN dotnet build 
RUN dotnet publish --no-restore -c Release -o domain

FROM mcr.microsoft.com/dotnet/core/aspnet
WORKDIR /dist
COPY --from=build /aspnet/domain .

CMD [ "dotnet", "BudgetMe.Domain.dll" ]

