# docker-compose.yml
version: "3.3"
services:
  db:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - BudgetMeNet
  app:
    build: .
    hostname: app
    depends_on:
      - db
    links:
      - db
    ports:
      - 4000:80
    networks:
      - BudgetMeNet
    environment:
      WAIT_HOSTS: db:5432
      ASPNETCORE_ENVIRONMENT: Development
  client:
    build: ./BudgetMe.Client/.
    hostname: client
    ports:
      - 5000:80
    networks:
      - BudgetMeNet
    depends_on:
      - db
    links:
      - app
      - db
    environment:
      WAIT_HOSTS: db:5432
      ASPNETCORE_ENVIRONMENT: Development
networks:
  BudgetMeNet:
    driver: bridge