# docker-compose.yml
version: "3.3"
services:
  postgres:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  app:
    build: .
    hostname: app
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 4000:80
    environment:
      WAIT_HOSTS: postgres:5432
  client:
    build: ./BudgetMe.Client/.
    hostname: client
    ports:
      - 5000:80
    depends_on:
      - postgres
    links:
      - app
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432